@startuml ジャイロセンサー検証システム_ステートマシン図

skinparam ActivityDiamondFontSize 12
skinparam ActivityFontSize 12
skinparam StateFontSize 12

legend top
[ジャイロセンサー検証システム_ステートマシン図]
[KAMOGAWorks] []
endlegend

[*] --> 初期化状態

state 初期化状態
初期化状態 : entry / デバイス初期化（IMU・フォースセンサー）

初期化状態 --> 待機状態 : 初期化完了

state 待機状態
待機状態 : do / フォースセンサーの入力監視

待機状態 --> キャリブレーション状態 : フォースセンサーON後OFF検出

state キャリブレーション状態
キャリブレーション状態 : entry / 静止状態でキャリブレーション実行

キャリブレーション状態 --> 計測中状態 : キャリブレーション完了

state 計測中状態 {

    [*] --> サンプリング

    state サンプリング
    サンプリング : do / 0.1秒ごとに各種API値（角速度, 加速度, 温度）を取得
    サンプリング : do / 計測結果をCSV形式で標準出力

}

計測中状態 --> 計測完了状態 : フォースセンサーON後OFF検出

state 計測完了状態
計測完了状態 : entry / 計測終了処理

計測完了状態 --> [*]

@enduml
