@startuml ジャイロセンサー検証システム_アクティビティ図

skinparam ActivityDiamondFontSize 12
skinparam ActivityFontSize 12

legend top
[ジャイロセンサー検証システム_アクティビティ図]
[KAMOGAWorks] [松野]
endlegend

start

:デバイス初期化（IMU・フォースセンサー）;

if (初期化成功?) then (はい)
else (いいえ)
    :エラー内容を通知;
    :安全終了処理;
    stop
endif

:フォースセンサーON後、OFFになるのを待つ;

:キャリブレーションを実行;

if (キャリブレーション成功?) then (はい)
else (いいえ)
    :エラー内容を通知;
    :安全終了処理;
    stop
endif

:停止要求フラグをfalseにする;
:異常終了要求フラグをfalseにする;

fork

partition データ計測・出力ループ {

    repeat

        :各種API値（X/Y/Z軸の角速度・加速度・温度）を取得;

        :異常値を除外せず、計測データとして保持;

        :計測結果をカンマ区切りで標準出力へ表示;

        if (CSV出力成功?) then (はい)
        else (いいえ)
            :エラー内容を通知;
            :異常終了要求フラグをtrueにする;
        endif

        :0.1秒待機;

    repeat while (停止要求フラグまたは異常終了要求フラグがtrueか?) is (いいえ) not (はい)

}

fork again

partition 停止割り込み処理 {

    repeat

        :フォースセンサー状態と\n異常終了要求フラグを確認;

    repeat while (フォースセンサーON後OFFまたは異常終了要求フラグを検出したか?) is (いいえ) not (はい)

    if (異常終了要求フラグがtrueか?) then (はい)
        :停止監視を終了;
    else (いいえ)
        :停止要求フラグをtrueにする;
    endif

}

end fork

if (異常終了要求フラグがtrueか?) then (はい)
    :安全終了処理;
else (いいえ)
    :計測終了;
endif

stop

@enduml


